[package]
name = "raw_mesh"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bytes = "1.3"
gltf.workspace = true
mimalloc = "0.1"
reqwest = { workspace = true, default-features = false, features = [
  "blocking",
  "rustls-tls",
] }

# TODO(cmc): is the crate actually gonna be called just 'rerun' in the end?
rerun = { package = "rerun_sdk", path = "../../crates/rerun_sdk" }
