[package]
name = "dna"
version = "0.9.1-rc.1"
edition = "2021"
rust-version = "1.72"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
rerun = { path = "../../../crates/rerun" }

itertools = "0.11"
rand = "0.8"
