[workspace]
resolver = "2"
members = [
    "crates/re_comms",
    "crates/re_data_store",
    "crates/re_log_types",
    "crates/re_string_interner",
    "crates/re_viewer",
    "crates/re_web_server",

    "examples/nyud",
    "examples/objectron",
    "examples/project_depth",
]


[profile.dev]
# opt-level = 1 # Speed up debug builds

[profile.release]
# debug = true # good for profilers

[profile.bench]
debug = true

