[package]
name = "re_error"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false


[lib]
crate-type = ["rlib"]


[dev-dependencies]
anyhow = "1"
