[package]
name = "re_log_types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false


[lib]
crate-type = ["dylib", "rlib"]


[features]
default = ["arrow_datagen"]

## Enable loading data from a file.
load = ["re_log_types_impl/load"]

## Add support for some math operations using [`glam`](https://crates.io/crates/glam/).
glam = ["re_log_types_impl/glam"]

## Add support for the [`puffin`](https://github.com/EmbarkStudios/puffin) profiler.
puffin = ["re_log_types_impl/puffin"]

## Enable saving data to a file.
save = ["re_log_types_impl/save"]

## Enable (de)serialization using serde.
serde = ["re_log_types_impl/serde"]

## Enables the `datagen` module, which exposes a number of tools for generating random data for
## tests and benchmarks.
arrow_datagen = ["re_log_types_impl/arrow_datagen"]


[dependencies]
re_log_types_dyn = { path = "./dyn" }
re_log_types_impl = { path = "./impl" }
