[package]
name = "re_data_store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false


[lib]
crate-type = ["dylib", "rlib"]


[features]
default = []

## Add support for the [`puffin`](https://github.com/EmbarkStudios/puffin) profiler.
puffin = ["re_data_store_impl/puffin"]

## Enable (de)serialization using serde.
serde = ["re_data_store_impl/serde"]


[dependencies]
re_data_store_dyn = { path = "./dyn" }
re_data_store_impl = { path = "./impl" }
