[package]
name = "re_log"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false


[lib]
crate-type = ["rlib"]


[dependencies]
log-once = "0.4"
tracing = "0.1"
