[package]
name = "re_viewer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
include = [
  "../../LICENSE-APACHE",
  "../../LICENSE-MIT",
  "**/*.rs",
  "Cargo.toml",
  "data/*",
]


[lib]
# TODO: offer cdyn only when going through maturin
crate-type = ["dylib", "rlib"]


[features]
default = ["puffin"]

## Add support for the [`puffin`](https://github.com/EmbarkStudios/puffin) profiler.
puffin = ["re_viewer_impl/puffin"]


[dependencies]
re_viewer_dyn = { path = "./dyn" }
re_viewer_impl = { path = "./impl" }
